from src.NonLin.bisection import bisection
from src.NonLin.fixed_point import fixed_point
from src.NonLin.integrate import integrate
from src.NonLin.midpoint import midpoint
from src.NonLin.newtonsys import newtonsys
from src.NonLin.newton import newton
from src.NonLin.ostrowski import ostrowski
from src.NonLin.polyfit import polyfit
from src.NonLin.polyval import polyval
from src.NonLin.simpson import simpson
from src.NonLin.trapezoid import trapezoid